framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    error_controller: 'twig.controller.error'  # Moved here
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

twig:
    # No 'error' or 'error_controller' here, since it's configured under framework.
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
